version: '3'
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/main
      - PASSWORD_HASH=73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8=
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./backend/app:/app
    command: npm run debug
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
