version: '3'
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./backend/app:/app
    command: npm run debug
